name: Test

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'

  schedule:
    - cron: '22 23 * * 5'

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
        java: [ '8', '11', '16' ]
        maven: [ '3.5.4', '3.6.3', '3.8.2' ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: ./
        with:
          java-version: ${{ matrix.java }}
          java-cache: maven
          maven-version: ${{ matrix.maven }}

      - run: mvn -V validate -Drequire.java=${{ matrix.java }} -Drequire.maven=${{ matrix.maven }}
        shell: bash

